### ISSUE TITLE
Как пофиксить ошибку "Необходимо ввести последние 4 цифры номера телефона."?

### ISSUE THREAD

**Issue by lifr0m** [kesha1225/pykwork#1]
Можно ли в программе ввести заранее эти 4 последних цифры, чтобы как-то обходить эту проверку?

**Comment by kesha1225** [comment]
Неа, это не через апи делается, а через веб, пока я это не реализовал, можно просто поставить прокси и ошибка пропадет

**Comment by lifr0m** [comment]
Хорошо, спасибо

**Comment by CrazyMan-IK** [comment]
@kesha1225 это очень легко фиксится, передачей последних 4 цифр номера в поле phone_last при получении токена

**Comment by kesha1225** [comment]
> 
> 
> @kesha1225 это очень легко фиксится, передачей последних 4 цифр номера в поле phone_last при получении токена

Просто параметром?

**Comment by kesha1225** [comment]
> 
> 
> Можно ли в программе ввести заранее эти 4 последних цифры, чтобы как-то обходить эту проверку?

Теперь можно через 
```
Kwork(login="login", password="password", phone_last="0102")
```
Можете попробовать, должно работать

**Comment by CrazyMan-IK** [comment]
@kesha1225 да обычным параметром, как логин и пароль. Там если запрос к https://api.kwork.ru с ключом отправить, возвращается страничка с описанием доступных методов, но работает она только в браузере и чтобы получить доступные методы можно отправить запрос именно к json файлу (там ниже на этой странице в коде есть нужный адрес), либо в браузере добавить ключ авторизации в запросе (помогут сторонние плагины)

**Comment by kesha1225** [comment]
> 
> 
> @kesha1225 да обычным параметром, как логин и пароль. Там если запрос к https://api.kwork.ru с ключом отправить, возвращается страничка с описанием доступных методов, но работает она только в браузере и чтобы получить доступные методы можно отправить запрос именно к json файлу (там ниже на этой странице в коде есть нужный адрес), либо в браузере добавить ключ авторизации в запросе (помогут сторонние плагины)

Нашел, вот он https://cdn.kwork.ru/js/openapi.json
