### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by revolexGeek** [kesha1225/pykwork#4]
Документация, которую необходимо открывать через "docs.html" не работает.
![image](https://github.com/kesha1225/pykwork/assets/86723750/18201a0b-2890-47e8-a2b2-9444fb209ff7)

Однако, json файлик со всеми указаниями работает:
![image](https://github.com/kesha1225/pykwork/assets/86723750/4b38a722-4432-4693-bc2e-76e36b42ef71)
![image](https://github.com/kesha1225/pykwork/assets/86723750/a6df6e56-e73b-4ab9-9f81-0251589ece92)

Хотелось бы конечно удобнее просматривать ветку запросов :)

**Comment by hoosnick** [comment]
просто поставь json на этот [сайт](https://editor.swagger.io/), и он автоматически преобразует json в yml.

![image](https://github.com/kesha1225/pykwork/assets/73847672/a69f7365-46f6-40bc-97bf-bb040ea6bc51)

![image](https://github.com/kesha1225/pykwork/assets/73847672/a429f162-8a01-41a3-986f-95fdd2efd1d4)

**Comment by revolexGeek** [comment]
Спасибо!
